#!/usr/bin/env bash
# © Mayanktaker Computers & Web Development | https://mayanktaker.com
# Interactive Setup & Customization Wizard for Mayanktaker Devbox
# Allows enabling/disabling components or installing full suite anytime

set -e

# Terminal color codes
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

CONF_FILE=".devbox.conf"
ENV_FILE=".env"

show_banner() {
    clear 2>/dev/null || true
    echo -e "${CYAN}========================================================================${NC}"
    echo -e "${GREEN}${BOLD}  🛠️  MAYANKTAKER DEVBOX — INTERACTIVE SETUP & CUSTOMIZATION WIZARD   ${NC}"
    echo -e "${CYAN}  © Mayanktaker Computers & Web Development | https://mayanktaker.com  ${NC}"
    echo -e "${CYAN}========================================================================${NC}"
    echo ""
}

# Load current configuration if available
load_config() {
    ENABLE_AI_AGENTS=${ENABLE_AI_AGENTS:-true}
    ENABLE_FLUTTER_ANDROID=${ENABLE_FLUTTER_ANDROID:-true}
    ENABLE_PLAYWRIGHT=${ENABLE_PLAYWRIGHT:-true}
    ENABLE_PHP=${ENABLE_PHP:-true}
    ENABLE_MYSQL=${ENABLE_MYSQL:-true}
    ENABLE_REDIS=${ENABLE_REDIS:-true}
    ENABLE_FIREBASE=${ENABLE_FIREBASE:-true}
    ENABLE_DEV_TOOLS=${ENABLE_DEV_TOOLS:-true}

    if [ -f "$CONF_FILE" ]; then
        source "$CONF_FILE"
    fi
}

# Helper function to set or replace env var in .env
set_env_var() {
    local key="$1"
    local val="$2"
    if [ ! -f "$ENV_FILE" ]; then
        cp .env.example "$ENV_FILE"
    fi
    if grep -q "^${key}=" "$ENV_FILE"; then
        sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
    else
        echo "${key}=${val}" >> "$ENV_FILE"
    fi
}

# Save configuration to .devbox.conf and update .env
save_config() {
    cat <<EOF > "$CONF_FILE"
# Mayanktaker Devbox Component Configuration
# Generated by Setup Wizard on $(date)
ENABLE_AI_AGENTS=$ENABLE_AI_AGENTS
ENABLE_FLUTTER_ANDROID=$ENABLE_FLUTTER_ANDROID
ENABLE_PLAYWRIGHT=$ENABLE_PLAYWRIGHT
ENABLE_PHP=$ENABLE_PHP
ENABLE_MYSQL=$ENABLE_MYSQL
ENABLE_REDIS=$ENABLE_REDIS
ENABLE_FIREBASE=$ENABLE_FIREBASE
ENABLE_DEV_TOOLS=$ENABLE_DEV_TOOLS
EOF

    set_env_var "ENABLE_AI_AGENTS" "$ENABLE_AI_AGENTS"
    set_env_var "ENABLE_FLUTTER_ANDROID" "$ENABLE_FLUTTER_ANDROID"
    set_env_var "ENABLE_PLAYWRIGHT" "$ENABLE_PLAYWRIGHT"
    set_env_var "ENABLE_PHP" "$ENABLE_PHP"
    set_env_var "ENABLE_MYSQL" "$ENABLE_MYSQL"
    set_env_var "ENABLE_REDIS" "$ENABLE_REDIS"
    set_env_var "ENABLE_FIREBASE" "$ENABLE_FIREBASE"
    set_env_var "ENABLE_DEV_TOOLS" "$ENABLE_DEV_TOOLS"

    # Set Docker Compose profiles
    PROFILES="default"
    if [ "$ENABLE_MYSQL" = "true" ]; then PROFILES="${PROFILES},mysql"; fi
    if [ "$ENABLE_REDIS" = "true" ]; then PROFILES="${PROFILES},redis"; fi
    set_env_var "COMPOSE_PROFILES" "$PROFILES"

    echo -e "${GREEN}[✓] Configuration saved to ${CONF_FILE} and ${ENV_FILE}${NC}"
}

# Interactive API Keys Config Helper
configure_keys() {
    show_banner
    echo -e "${BOLD}🔑 Configure AI Provider, Router & Cloud API Keys (.env)${NC}"
    echo -e "${CYAN}Press Enter to keep existing key value, or type a new key value.${NC}"
    echo ""

    if [ -f "$ENV_FILE" ]; then
        source "$ENV_FILE" 2>/dev/null || true
    fi

    prompt_key() {
        local varname="$1"
        local label="$2"
        eval "local current=\$$varname"
        local masked=""
        if [ -n "$current" ]; then
            masked="[Configured: ${current:0:6}...]"
        else
            masked="[Not set]"
        fi
        read -p "$label $masked: " input_val
        if [ -n "$input_val" ]; then
            set_env_var "$varname" "$input_val"
            echo -e "${GREEN}  ✓ Updated $varname${NC}"
        else
            echo -e "${CYAN}  - Kept $varname${NC}"
        fi
    }

    prompt_key "OPENAI_API_KEY" "OpenAI API Key (GPT-4o/Codex)"
    prompt_key "ANTHROPIC_API_KEY" "Anthropic API Key (Claude Code)"
    prompt_key "GEMINI_API_KEY" "Google Gemini / Antigravity API Key"
    prompt_key "OPENROUTER_API_KEY" "OpenRouter API Key"
    prompt_key "KILO_API_KEY" "Kilo Code API Key"
    prompt_key "OPENCODE_API_KEY" "OpenCode API Key"
    prompt_key "DEVIN_API_KEY" "Devin AI API Key"
    prompt_key "KIMI_API_KEY" "Kimi Code API Key"
    prompt_key "CURSOR_API_KEY" "Cursor API Key"
    prompt_key "DEEPSEEK_API_KEY" "DeepSeek API Key"
    prompt_key "MISTRAL_API_KEY" "Mistral AI API Key"
    prompt_key "GITHUB_TOKEN" "GitHub Personal Access Token"

    echo ""
    echo -e "${GREEN}[✓] API Keys configured in ${ENV_FILE}!${NC}"
    sleep 2
}

# Summary table view
show_summary() {
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    echo -e "${BOLD}               CURRENT DEVBOX COMPONENT CONFIGURATION                   ${NC}"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    printf "  %-35s | %-15s\n" "Component / Module" "Status"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    
    print_row() {
        local name="$1"
        local val="$2"
        if [ "$val" = "true" ]; then
            printf "  %-35s | ${GREEN}%-15s${NC}\n" "$name" "[✓] ENABLED"
        else
            printf "  %-35s | ${RED}%-15s${NC}\n" "$name" "[✗] DISABLED"
        fi
    }

    print_row "🤖 20+ AI Agent CLIs (Claude, Kilo, etc)" "$ENABLE_AI_AGENTS"
    print_row "📱 Mobile Dev (Flutter + Android SDK)" "$ENABLE_FLUTTER_ANDROID"
    print_row "🎭 Browser Testing (Chromium + Playwright)" "$ENABLE_PLAYWRIGHT"
    print_row "🐘 PHP 8.5 & Composer Ecosystem" "$ENABLE_PHP"
    print_row "🐬 MySQL 8.4 Database + phpMyAdmin" "$ENABLE_MYSQL"
    print_row "⚡ Redis 8 Cache + Redis Commander" "$ENABLE_REDIS"
    print_row "🔥 Firebase CLI & Emulator Suite" "$ENABLE_FIREBASE"
    print_row "🧰 Dev TUI Tools (lazygit, bat, eza)" "$ENABLE_DEV_TOOLS"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    echo ""
}

# Install All Preset
install_all() {
    ENABLE_AI_AGENTS=true
    ENABLE_FLUTTER_ANDROID=true
    ENABLE_PLAYWRIGHT=true
    ENABLE_PHP=true
    ENABLE_MYSQL=true
    ENABLE_REDIS=true
    ENABLE_FIREBASE=true
    ENABLE_DEV_TOOLS=true
    save_config
    echo -e "${GREEN}${BOLD}[🚀] FULL SUPERCHARGED SUITE ENABLED! All features activated.${NC}"
}

# Minimal Preset
install_minimal() {
    ENABLE_AI_AGENTS=true
    ENABLE_FLUTTER_ANDROID=false
    ENABLE_PLAYWRIGHT=false
    ENABLE_PHP=false
    ENABLE_MYSQL=false
    ENABLE_REDIS=false
    ENABLE_FIREBASE=false
    ENABLE_DEV_TOOLS=true
    save_config
    echo -e "${YELLOW}[⚡] MINIMAL CORE SUITE ENABLED! (AI Agents + Node 24 + VS Code Web).${NC}"
}

# Interactive Whiptail Checklist Menu
custom_whiptail_menu() {
    local CHOICE
    CHOICE=$(whiptail --title "Mayanktaker Devbox Custom Component Selection" \
        --checklist "Use Spacebar to toggle items ON/OFF, then press Enter:" 20 75 8 \
        "AI_AGENTS" "20+ AI Agent CLIs (Claude, Kilo, Gemini, Devin, etc)" $([ "$ENABLE_AI_AGENTS" = "true" ] && echo "ON" || echo "OFF") \
        "FLUTTER_ANDROID" "Flutter SDK, Dart & Android SDK API 35" $([ "$ENABLE_FLUTTER_ANDROID" = "true" ] && echo "ON" || echo "OFF") \
        "PLAYWRIGHT" "Chromium & Playwright Browser Automation" $([ "$ENABLE_PLAYWRIGHT" = "true" ] && echo "ON" || echo "OFF") \
        "PHP" "PHP 8.5 & Composer Ecosystem" $([ "$ENABLE_PHP" = "true" ] && echo "ON" || echo "OFF") \
        "MYSQL" "MySQL 8.4 Database Container + phpMyAdmin" $([ "$ENABLE_MYSQL" = "true" ] && echo "ON" || echo "OFF") \
        "REDIS" "Redis 8 Cache Container + Redis Commander" $([ "$ENABLE_REDIS" = "true" ] && echo "ON" || echo "OFF") \
        "FIREBASE" "Firebase CLI & Local Emulator Suite" $([ "$ENABLE_FIREBASE" = "true" ] && echo "ON" || echo "OFF") \
        "DEV_TOOLS" "Developer Productivity TUI Tools (lazygit, bat, etc)" $([ "$ENABLE_DEV_TOOLS" = "true" ] && echo "ON" || echo "OFF") \
        3>&1 1>&2 2>&3) || return

    ENABLE_AI_AGENTS=false
    ENABLE_FLUTTER_ANDROID=false
    ENABLE_PLAYWRIGHT=false
    ENABLE_PHP=false
    ENABLE_MYSQL=false
    ENABLE_REDIS=false
    ENABLE_FIREBASE=false
    ENABLE_DEV_TOOLS=false

    for item in $CHOICE; do
        case $(echo "$item" | tr -d '"') in
            AI_AGENTS) ENABLE_AI_AGENTS=true ;;
            FLUTTER_ANDROID) ENABLE_FLUTTER_ANDROID=true ;;
            PLAYWRIGHT) ENABLE_PLAYWRIGHT=true ;;
            PHP) ENABLE_PHP=true ;;
            MYSQL) ENABLE_MYSQL=true ;;
            REDIS) ENABLE_REDIS=true ;;
            FIREBASE) ENABLE_FIREBASE=true ;;
            DEV_TOOLS) ENABLE_DEV_TOOLS=true ;;
        esac
    done

    save_config
}

# CLI Terminal Custom Menu
custom_cli_menu() {
    toggle_var() {
        local name="$1"
        eval "local val=\$$name"
        if [ "$val" = "true" ]; then
            eval "$name=false"
        else
            eval "$name=true"
        fi
    }

    while true; do
        show_banner
        show_summary
        echo -e "${BOLD}Select a component number to toggle ON/OFF, or 'S' to Save & Exit:${NC}"
        echo "  [1] Toggle AI Agent CLIs"
        echo "  [2] Toggle Mobile Dev (Flutter & Android SDK)"
        echo "  [3] Toggle Browser Testing (Chromium & Playwright)"
        echo "  [4] Toggle PHP 8.5 & Composer"
        echo "  [5] Toggle MySQL 8.4 Database + phpMyAdmin"
        echo "  [6] Toggle Redis 8 Cache + Redis Commander"
        echo "  [7] Toggle Firebase CLI & Emulators"
        echo "  [8] Toggle Dev TUI Tools (lazygit, bat, etc)"
        echo "  [A] Enable ALL Components"
        echo "  [S] Save & Finish"
        echo ""
        read -p "Enter choice [1-8, A, S]: " input_choice

        case "$input_choice" in
            1) toggle_var "ENABLE_AI_AGENTS" ;;
            2) toggle_var "ENABLE_FLUTTER_ANDROID" ;;
            3) toggle_var "ENABLE_PLAYWRIGHT" ;;
            4) toggle_var "ENABLE_PHP" ;;
            5) toggle_var "ENABLE_MYSQL" ;;
            6) toggle_var "ENABLE_REDIS" ;;
            7) toggle_var "ENABLE_FIREBASE" ;;
            8) toggle_var "ENABLE_DEV_TOOLS" ;;
            [aA]) install_all ; break ;;
            [sS]) save_config ; break ;;
            *) echo -e "${RED}Invalid option.${NC}" ; sleep 1 ;;
        esac
    done
}

# Main Wizard Menu Router
run_wizard() {
    load_config
    show_banner
    show_summary

    echo -e "${BOLD}Choose a Setup Wizard Option:${NC}"
    echo -e "  ${GREEN}${BOLD}[1] 🚀 INSTALL ALL (Full Supercharged Suite - Recommended)${NC}"
    echo -e "  ${CYAN}[2] 🎛️  Custom Selection (Toggle components ON/OFF)${NC}"
    echo -e "  ${YELLOW}[3] ⚡ Minimal Suite (Core AI Agents + Node 24 + VS Code Web)${NC}"
    echo -e "  ${CYAN}[4] 🔑 Configure API Keys (.env helper)${NC}"
    echo -e "  [5] 🚪 Exit without changes"
    echo ""
    read -p "Select option [1-5]: " main_choice

    case "$main_choice" in
        1)
            install_all
            ;;
        2)
            if [ -t 0 ] && command -v whiptail >/dev/null 2>&1; then
                custom_whiptail_menu
            else
                custom_cli_menu
            fi
            ;;
        3)
            install_minimal
            ;;
        4)
            configure_keys
            run_wizard
            return
            ;;
        5)
            echo -e "${YELLOW}Exited without changing configuration.${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid selection.${NC}"
            exit 1
            ;;
    esac

    show_banner
    show_summary

    read -p "Would you like to build and start Devbox now? (Y/n): " confirm_build
    case "$confirm_build" in
        [nN]*)
            echo -e "${YELLOW}Setup complete! Run './manage.sh build && ./manage.sh up' when ready.${NC}"
            ;;
        *)
            echo -e "${GREEN}[+] Starting build and launch sequence...${NC}"
            ./manage.sh build
            ./manage.sh up
            ;;
    esac
}

run_wizard
