#!/usr/bin/env bash
# © Mayanktaker Computers & Web Development | https://mayanktaker.com
# Interactive Setup & Customization Wizard for Mayanktaker Devbox
# Allows enabling/disabling components or installing full suite anytime

set -e

# Terminal color codes
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

CONF_FILE=".devbox.conf"
ENV_FILE=".env"

show_banner() {
    clear 2>/dev/null || true
    echo -e "${CYAN}========================================================================${NC}"
    echo -e "${GREEN}${BOLD}  🛠️  MAYANKTAKER DEVBOX — INTERACTIVE SETUP & CUSTOMIZATION WIZARD   ${NC}"
    echo -e "${CYAN}  © Mayanktaker Computers & Web Development | https://mayanktaker.com  ${NC}"
    echo -e "${CYAN}========================================================================${NC}"
    echo ""
}

# Load current configuration if available
load_config() {
    ENABLE_AI_AGENTS=${ENABLE_AI_AGENTS:-true}
    ENABLE_FLUTTER_ANDROID=${ENABLE_FLUTTER_ANDROID:-true}
    ENABLE_EXPO=${ENABLE_EXPO:-true}
    ENABLE_FASTLANE=${ENABLE_FASTLANE:-true}
    ENABLE_KOTLIN=${ENABLE_KOTLIN:-true}
    ENABLE_LIGHTHOUSE=${ENABLE_LIGHTHOUSE:-true}
    ENABLE_WATCHMAN=${ENABLE_WATCHMAN:-true}
    ENABLE_PLAYWRIGHT=${ENABLE_PLAYWRIGHT:-true}
    ENABLE_PHP=${ENABLE_PHP:-true}
    ENABLE_MYSQL=${ENABLE_MYSQL:-true}
    ENABLE_POSTGRES=${ENABLE_POSTGRES:-false}
    ENABLE_MONGO=${ENABLE_MONGO:-false}
    ENABLE_REDIS=${ENABLE_REDIS:-true}
    ENABLE_FIREBASE=${ENABLE_FIREBASE:-true}
    ENABLE_DEV_TOOLS=${ENABLE_DEV_TOOLS:-true}
    ENABLE_COMPOSER=${ENABLE_COMPOSER:-true}
    ENABLE_BUN=${ENABLE_BUN:-true}
    ENABLE_UV=${ENABLE_UV:-true}
    ENABLE_RUST=${ENABLE_RUST:-true}
    ENABLE_GO=${ENABLE_GO:-false}
    ENABLE_DENO=${ENABLE_DENO:-false}
    ENABLE_CPP_TOOLCHAIN=${ENABLE_CPP_TOOLCHAIN:-false}
    ENABLE_ZSH=${ENABLE_ZSH:-true}
    ENABLE_FISH=${ENABLE_FISH:-false}
    ENABLE_VSCODE_WEB=${ENABLE_VSCODE_WEB:-true}
    ENABLE_VSCODIUM_WEB=${ENABLE_VSCODIUM_WEB:-true}
    ENABLE_NEOVIM=${ENABLE_NEOVIM:-true}
    ENABLE_MICRO=${ENABLE_MICRO:-true}
    ENABLE_HELIX=${ENABLE_HELIX:-false}
    ENABLE_WEB_TOOLING=${ENABLE_WEB_TOOLING:-true}
    ENABLE_POSTGRES_CLIENT=${ENABLE_POSTGRES_CLIENT:-true}
    DB_ENGINE=${DB_ENGINE:-mysql}
    DB_ENGINE_IMAGE=${DB_ENGINE_IMAGE:-mysql:8.4}
    REDIS_ENGINE_IMAGE=${REDIS_ENGINE_IMAGE:-redis:8-alpine}
    NODE_VERSION=${NODE_VERSION:-24}
    PHP_VERSION=${PHP_VERSION:-8.5}
    JAVA_VERSION=${JAVA_VERSION:-21}

    if [ -f "$CONF_FILE" ]; then
        source "$CONF_FILE"
    fi
}

# Helper function to set or replace env var in .env
set_env_var() {
    local key="$1"
    local val="$2"
    if [ ! -f "$ENV_FILE" ]; then
        cp .env.example "$ENV_FILE"
    fi
    if grep -q "^${key}=" "$ENV_FILE"; then
        sed -i "s|^${key}=.*|${key}=${val}|" "$ENV_FILE"
    else
        echo "${key}=${val}" >> "$ENV_FILE"
    fi
}

# Save configuration to .devbox.conf and update .env
save_config() {
    cat <<EOF > "$CONF_FILE"
# Mayanktaker Devbox Component Configuration
# Generated by Setup Wizard on $(date)
ENABLE_AI_AGENTS=$ENABLE_AI_AGENTS
ENABLE_FLUTTER_ANDROID=$ENABLE_FLUTTER_ANDROID
ENABLE_EXPO=$ENABLE_EXPO
ENABLE_FASTLANE=$ENABLE_FASTLANE
ENABLE_KOTLIN=$ENABLE_KOTLIN
ENABLE_LIGHTHOUSE=$ENABLE_LIGHTHOUSE
ENABLE_WATCHMAN=$ENABLE_WATCHMAN
ENABLE_PLAYWRIGHT=$ENABLE_PLAYWRIGHT
ENABLE_PHP=$ENABLE_PHP
ENABLE_MYSQL=$ENABLE_MYSQL
ENABLE_POSTGRES=$ENABLE_POSTGRES
ENABLE_MONGO=$ENABLE_MONGO
ENABLE_REDIS=$ENABLE_REDIS
ENABLE_FIREBASE=$ENABLE_FIREBASE
ENABLE_DEV_TOOLS=$ENABLE_DEV_TOOLS
ENABLE_COMPOSER=$ENABLE_COMPOSER
ENABLE_BUN=$ENABLE_BUN
ENABLE_UV=$ENABLE_UV
ENABLE_RUST=$ENABLE_RUST
ENABLE_GO=$ENABLE_GO
ENABLE_DENO=$ENABLE_DENO
ENABLE_CPP_TOOLCHAIN=$ENABLE_CPP_TOOLCHAIN
ENABLE_ZSH=$ENABLE_ZSH
ENABLE_FISH=$ENABLE_FISH
ENABLE_VSCODE_WEB=$ENABLE_VSCODE_WEB
ENABLE_VSCODIUM_WEB=$ENABLE_VSCODIUM_WEB
ENABLE_NEOVIM=$ENABLE_NEOVIM
ENABLE_MICRO=$ENABLE_MICRO
ENABLE_HELIX=$ENABLE_HELIX
ENABLE_WEB_TOOLING=$ENABLE_WEB_TOOLING
ENABLE_POSTGRES_CLIENT=$ENABLE_POSTGRES_CLIENT
DB_ENGINE=$DB_ENGINE
DB_ENGINE_IMAGE=$DB_ENGINE_IMAGE
REDIS_ENGINE_IMAGE=$REDIS_ENGINE_IMAGE
NODE_VERSION=$NODE_VERSION
PHP_VERSION=$PHP_VERSION
JAVA_VERSION=$JAVA_VERSION
EOF

    set_env_var "ENABLE_AI_AGENTS" "$ENABLE_AI_AGENTS"
    set_env_var "ENABLE_FLUTTER_ANDROID" "$ENABLE_FLUTTER_ANDROID"
    set_env_var "ENABLE_EXPO" "$ENABLE_EXPO"
    set_env_var "ENABLE_FASTLANE" "$ENABLE_FASTLANE"
    set_env_var "ENABLE_KOTLIN" "$ENABLE_KOTLIN"
    set_env_var "ENABLE_LIGHTHOUSE" "$ENABLE_LIGHTHOUSE"
    set_env_var "ENABLE_WATCHMAN" "$ENABLE_WATCHMAN"
    set_env_var "ENABLE_PLAYWRIGHT" "$ENABLE_PLAYWRIGHT"
    set_env_var "ENABLE_PHP" "$ENABLE_PHP"
    set_env_var "ENABLE_MYSQL" "$ENABLE_MYSQL"
    set_env_var "ENABLE_POSTGRES" "$ENABLE_POSTGRES"
    set_env_var "ENABLE_MONGO" "$ENABLE_MONGO"
    set_env_var "ENABLE_REDIS" "$ENABLE_REDIS"
    set_env_var "ENABLE_FIREBASE" "$ENABLE_FIREBASE"
    set_env_var "ENABLE_DEV_TOOLS" "$ENABLE_DEV_TOOLS"
    set_env_var "ENABLE_COMPOSER" "$ENABLE_COMPOSER"
    set_env_var "ENABLE_BUN" "$ENABLE_BUN"
    set_env_var "ENABLE_UV" "$ENABLE_UV"
    set_env_var "ENABLE_RUST" "$ENABLE_RUST"
    set_env_var "ENABLE_GO" "$ENABLE_GO"
    set_env_var "ENABLE_DENO" "$ENABLE_DENO"
    set_env_var "ENABLE_CPP_TOOLCHAIN" "$ENABLE_CPP_TOOLCHAIN"
    set_env_var "ENABLE_ZSH" "$ENABLE_ZSH"
    set_env_var "ENABLE_FISH" "$ENABLE_FISH"
    set_env_var "ENABLE_VSCODE_WEB" "$ENABLE_VSCODE_WEB"
    set_env_var "ENABLE_VSCODIUM_WEB" "$ENABLE_VSCODIUM_WEB"
    set_env_var "ENABLE_NEOVIM" "$ENABLE_NEOVIM"
    set_env_var "ENABLE_MICRO" "$ENABLE_MICRO"
    set_env_var "ENABLE_HELIX" "$ENABLE_HELIX"
    set_env_var "ENABLE_WEB_TOOLING" "$ENABLE_WEB_TOOLING"
    set_env_var "ENABLE_POSTGRES_CLIENT" "$ENABLE_POSTGRES_CLIENT"
    set_env_var "DB_ENGINE" "$DB_ENGINE"
    set_env_var "DB_ENGINE_IMAGE" "$DB_ENGINE_IMAGE"
    set_env_var "REDIS_ENGINE_IMAGE" "$REDIS_ENGINE_IMAGE"
    set_env_var "NODE_VERSION" "$NODE_VERSION"
    set_env_var "PHP_VERSION" "$PHP_VERSION"
    set_env_var "JAVA_VERSION" "$JAVA_VERSION"

    # Set Docker Compose profiles
    PROFILES="default"
    if [ "$ENABLE_MYSQL" = "true" ]; then PROFILES="${PROFILES},mysql"; fi
    if [ "$ENABLE_REDIS" = "true" ]; then PROFILES="${PROFILES},redis"; fi
    if [ "$ENABLE_POSTGRES" = "true" ]; then PROFILES="${PROFILES},postgres"; fi
    if [ "$ENABLE_MONGO" = "true" ]; then PROFILES="${PROFILES},mongo"; fi
    set_env_var "COMPOSE_PROFILES" "$PROFILES"

    echo -e "${GREEN}[✓] Configuration saved to ${CONF_FILE} and ${ENV_FILE}${NC}"
}

# Database & Cache Selection Menu
select_db_engines() {
    show_banner
    echo -e "${BOLD}🗄️ Database & Cache Service Options${NC}"
    echo ""

    echo -e "${BOLD}1. Relational Database (Port 3306):${NC}"
    echo -e "   [1] 🐬 MySQL 8.4 LTS (${GREEN}Recommended Default${NC})"
    echo -e "   [2] 🦭 MariaDB 11.4 LTS (Open-Source Fork)"
    read -p "Select MySQL engine [1-2, Enter=1]: " db_choice
    case "$db_choice" in
        2) DB_ENGINE="mariadb"; DB_ENGINE_IMAGE="mariadb:11.4" ;;
        *) DB_ENGINE="mysql"; DB_ENGINE_IMAGE="mysql:8.4" ;;
    esac

    echo ""
    echo -e "${BOLD}2. In-Memory Cache Engine (Port 6379):${NC}"
    echo -e "   [1] ⚡ Redis 8 Alpine (${GREEN}Recommended Default${NC})"
    echo -e "   [2] 🍃 KeyDB (Multithreaded Redis Alternative)"
    read -p "Select Redis engine [1-2, Enter=1]: " redis_choice
    case "$redis_choice" in
        2) REDIS_ENGINE_IMAGE="eqalpha/keydb:latest" ;;
        *) REDIS_ENGINE_IMAGE="redis:8-alpine" ;;
    esac

    echo ""
    echo -e "${BOLD}3. PostgreSQL 17 + pgAdmin 4 Container (Port 5432 / 8088):${NC}"
    read -p "Enable PostgreSQL container service? (y/N): " pg_choice
    case "$pg_choice" in
        [yY]*) ENABLE_POSTGRES=true ;;
        *) ENABLE_POSTGRES=false ;;
    esac

    echo ""
    echo -e "${BOLD}4. MongoDB 8 + Mongo Express Container (Port 27017 / 8089):${NC}"
    read -p "Enable MongoDB container service? (y/N): " mongo_choice
    case "$mongo_choice" in
        [yY]*) ENABLE_MONGO=true ;;
        *) ENABLE_MONGO=false ;;
    esac

    save_config
    echo -e "${GREEN}[✓] Database & Cache configuration updated!${NC}"
    sleep 2
}

# Shells & Editors Customizer
select_shells_editors() {
    show_banner
    echo -e "${BOLD}💻 Shells & Web / Terminal Editors Selection${NC}"
    echo ""

    echo -e "${BOLD}1. Web IDE Choice (Port 8085 / 8084):${NC}"
    echo -e "   [1] 💙 Install BOTH VS Code Web (MS) & VSCodium Web (Open-VSX Telemetry-Free) (${GREEN}Recommended Default${NC})"
    echo -e "   [2] 🔷 VS Code Web only (code-server - Port 8085)"
    echo -e "   [3] 🛡️ VSCodium Web only (open-vsx Telemetry-Free - Port 8084)"
    read -p "Select Web IDE option [1-3, Enter=1]: " ide_choice
    case "$ide_choice" in
        2) ENABLE_VSCODE_WEB=true; ENABLE_VSCODIUM_WEB=false ;;
        3) ENABLE_VSCODE_WEB=false; ENABLE_VSCODIUM_WEB=true ;;
        *) ENABLE_VSCODE_WEB=true; ENABLE_VSCODIUM_WEB=true ;;
    esac

    echo ""
    echo -e "${BOLD}2. Command Shells:${NC}"
    read -p "Install Zsh + Starship prompt? (Y/n): " zsh_c
    case "$zsh_c" in [nN]*) ENABLE_ZSH=false ;; *) ENABLE_ZSH=true ;; esac

    read -p "Install Fish Shell? (y/N): " fish_c
    case "$fish_c" in [yY]*) ENABLE_FISH=true ;; *) ENABLE_FISH=false ;; esac

    echo ""
    echo -e "${BOLD}3. Terminal Text Editors:${NC}"
    read -p "Install Neovim + Vim? (Y/n): " nvim_c
    case "$nvim_c" in [nN]*) ENABLE_NEOVIM=false ;; *) ENABLE_NEOVIM=true ;; esac

    read -p "Install Micro Editor? (Y/n): " micro_c
    case "$micro_c" in [nN]*) ENABLE_MICRO=false ;; *) ENABLE_MICRO=true ;; esac

    read -p "Install Helix Editor? (y/N): " helix_c
    case "$helix_c" in [yY]*) ENABLE_HELIX=true ;; *) ENABLE_HELIX=false ;; esac

    save_config
    echo -e "${GREEN}[✓] Shells and Editors updated!${NC}"
    sleep 2
}

# Interactive Stack Version Customizer
select_stack_versions() {
    show_banner
    echo -e "${BOLD}⚙️ Customize Stack Runtime Versions (Node, PHP, Java)${NC}"
    echo -e "${CYAN}Recommended default versions are pre-selected.${NC}"
    echo ""

    echo -e "${BOLD}1. Select Node.js Version:${NC}"
    echo -e "   [1] Node.js 24 LTS (${GREEN}Recommended Default - Active LTS${NC})"
    echo -e "   [2] Node.js 26 Current (Latest features)"
    read -p "Select Node.js version [1-2, Enter=24]: " node_choice
    case "$node_choice" in
        2) NODE_VERSION="26" ;;
        *) NODE_VERSION="24" ;;
    esac

    echo ""
    echo -e "${BOLD}2. Select PHP Version:${NC}"
    echo -e "   [1] PHP 8.5 (${GREEN}Recommended Default - Latest Stable${NC})"
    echo -e "   [2] PHP 8.4 (Active Support)"
    read -p "Select PHP version [1-2, Enter=8.5]: " php_choice
    case "$php_choice" in
        2) PHP_VERSION="8.4" ;;
        *) PHP_VERSION="8.5" ;;
    esac

    echo ""
    echo -e "${BOLD}3. Select Java JDK Version:${NC}"
    echo -e "   [1] Java 21 JDK (${GREEN}Recommended Default - Current LTS${NC})"
    echo -e "   [2] Java 17 JDK (Legacy LTS)"
    read -p "Select Java version [1-2, Enter=21]: " java_choice
    case "$java_choice" in
        2) JAVA_VERSION="17" ;;
        *) JAVA_VERSION="21" ;;
    esac

    save_config
    echo -e "${GREEN}[✓] Stack versions updated: Node.js $NODE_VERSION, PHP $PHP_VERSION, Java $JAVA_VERSION${NC}"
    sleep 2
}

# Interactive API Keys Config Helper
configure_keys() {
    show_banner
    echo -e "${BOLD}🔑 Configure AI Provider, Router & Cloud API Keys (.env)${NC}"
    echo -e "${CYAN}Press Enter to keep existing key value, or type a new key value.${NC}"
    echo ""

    if [ -f "$ENV_FILE" ]; then
        source "$ENV_FILE" 2>/dev/null || true
    fi

    prompt_key() {
        local varname="$1"
        local label="$2"
        eval "local current=\$$varname"
        local masked=""
        if [ -n "$current" ]; then
            masked="[Configured: ${current:0:6}...]"
        else
            masked="[Not set]"
        fi
        read -p "$label $masked: " input_val
        if [ -n "$input_val" ]; then
            set_env_var "$varname" "$input_val"
            echo -e "${GREEN}  ✓ Updated $varname${NC}"
        else
            echo -e "${CYAN}  - Kept $varname${NC}"
        fi
    }

    prompt_key "OPENAI_API_KEY" "OpenAI API Key (GPT-4o/Codex)"
    prompt_key "ANTHROPIC_API_KEY" "Anthropic API Key (Claude Code)"
    prompt_key "GEMINI_API_KEY" "Google Gemini / Antigravity API Key"
    prompt_key "OPENROUTER_API_KEY" "OpenRouter API Key"
    prompt_key "KILO_API_KEY" "Kilo Code API Key"
    prompt_key "OPENCODE_API_KEY" "OpenCode API Key"
    prompt_key "DEVIN_API_KEY" "Devin AI API Key"
    prompt_key "KIMI_API_KEY" "Kimi Code API Key"
    prompt_key "CURSOR_API_KEY" "Cursor API Key"
    prompt_key "DEEPSEEK_API_KEY" "DeepSeek API Key"
    prompt_key "MISTRAL_API_KEY" "Mistral AI API Key"
    prompt_key "GITHUB_TOKEN" "GitHub Personal Access Token"

    echo ""
    echo -e "${GREEN}[✓] API Keys configured in ${ENV_FILE}!${NC}"
    sleep 2
}

# Host Permissions Pre-Check Helper
run_permissions_check() {
    show_banner
    echo -e "${BOLD}🔒 Host Permissions & Docker Group Pre-Check${NC}"
    echo ""
    mkdir -p workspace devbox_config backups
    chmod -R 775 workspace devbox_config backups 2>/dev/null || true
    
    if command -v docker >/dev/null 2>&1; then
        if ! groups "$USER" 2>/dev/null | grep -q "\bdocker\b"; then
            echo -e "${YELLOW}[!] User '$USER' is not in the 'docker' group.${NC}"
            read -p "Would you like to add '$USER' to the docker group? (Y/n): " add_doc
            case "$add_doc" in
                [nN]*) echo -e "${YELLOW}Skipped adding to docker group.${NC}" ;;
                *) sudo usermod -aG docker "$USER" && echo -e "${GREEN}[✓] Added $USER to docker group!${NC}" ;;
            esac
        else
            echo -e "${GREEN}  ✓ Docker group membership OK${NC}"
        fi
    fi

    if [ ! -w "workspace" ]; then
        echo -e "${YELLOW}[!] Workspace is not writable. Fixing...${NC}"
        chmod -R 775 workspace devbox_config backups 2>/dev/null || true
    else
        echo -e "${GREEN}  ✓ Workspace permissions OK${NC}"
    fi

    echo ""
    echo -e "${GREEN}[✓] Permissions check complete!${NC}"
    sleep 2
}

# Summary table view
show_summary() {
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    echo -e "${BOLD}               CURRENT DEVBOX COMPONENT CONFIGURATION                   ${NC}"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    printf "  %-35s | %-20s\n" "Component / Category" "Status / Selection"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    
    print_row() {
        local name="$1"
        local val="$2"
        if [ "$val" = "true" ]; then
            printf "  %-35s | ${GREEN}%-20s${NC}\n" "$name" "[✓] ENABLED"
        else
            printf "  %-35s | ${RED}%-20s${NC}\n" "$name" "[✗] DISABLED"
        fi
    }

    print_row "🤖 20+ AI Agent CLIs (Claude, Kilo, etc)" "$ENABLE_AI_AGENTS"
    print_row "🔷 VS Code Web (code-server - MS)" "$ENABLE_VSCODE_WEB"
    print_row "🛡️ VSCodium Web (open-vsx Telemetry-Free)" "$ENABLE_VSCODIUM_WEB"
    print_row "📱 Mobile Dev (Flutter + Android SDK)" "$ENABLE_FLUTTER_ANDROID"
    print_row "⚛️ React Native Expo CLI & eas-cli" "$ENABLE_EXPO"
    print_row "🚀 Fastlane Mobile Release Automation" "$ENABLE_FASTLANE"
    print_row "🎯 Kotlin Compiler (kotlinc)" "$ENABLE_KOTLIN"
    print_row "👁️ Watchman React Native Hot Reload" "$ENABLE_WATCHMAN"
    print_row "🎭 Browser Testing (Chromium + Playwright)" "$ENABLE_PLAYWRIGHT"
    print_row "🚥 Lighthouse Web Performance Audit" "$ENABLE_LIGHTHOUSE"
    print_row "🐘 PHP Engine" "$ENABLE_PHP"
    if [ "$ENABLE_PHP" = "true" ]; then
        printf "  %-35s | ${CYAN}%-20s${NC}\n" "   ├─ PHP Version" "[PHP $PHP_VERSION]"
        print_row "   └─ Composer Package Manager" "$ENABLE_COMPOSER"
    fi
    printf "  %-35s | ${CYAN}%-20s${NC}\n" "🟢 Node.js Runtime Version" "[Node.js $NODE_VERSION LTS]"
    print_row "🌐 Web Scaffolding (Astro, Next, Vite)" "$ENABLE_WEB_TOOLING"
    print_row "🍞 Bun JS/TS Runtime & PM" "$ENABLE_BUN"
    print_row "⚡ uv Python Package Manager" "$ENABLE_UV"
    print_row "🦀 Rust Toolchain (cargo, rustc)" "$ENABLE_RUST"
    print_row "🐹 Go Language (Golang)" "$ENABLE_GO"
    print_row "🦕 Deno TS/JS Runtime" "$ENABLE_DENO"
    print_row "🛠️ C/C++ Clang 18 & CMake Toolchain" "$ENABLE_CPP_TOOLCHAIN"
    printf "  %-35s | ${CYAN}%-20s${NC}\n" "☕ Java JDK Version" "[Java $JAVA_VERSION JDK]"
    print_row "🐚 Zsh + Starship Prompt" "$ENABLE_ZSH"
    print_row "🐟 Fish Shell" "$ENABLE_FISH"
    print_row "📝 Neovim & Vim Text Editor" "$ENABLE_NEOVIM"
    print_row "✏️ Micro Text Editor" "$ENABLE_MICRO"
    print_row "🛸 Helix Editor" "$ENABLE_HELIX"
    print_row "🐬 MySQL / MariaDB Database" "$ENABLE_MYSQL"
    if [ "$ENABLE_MYSQL" = "true" ]; then
        printf "  %-35s | ${CYAN}%-20s${NC}\n" "   └─ DB Engine Image" "[$DB_ENGINE_IMAGE]"
    fi
    print_row "🐘 PostgreSQL 17 + pgAdmin 4" "$ENABLE_POSTGRES"
    print_row "🍃 MongoDB 8 + Mongo Express" "$ENABLE_MONGO"
    print_row "⚡ Redis / KeyDB Cache Container" "$ENABLE_REDIS"
    if [ "$ENABLE_REDIS" = "true" ]; then
        printf "  %-35s | ${CYAN}%-20s${NC}\n" "   └─ Cache Engine Image" "[$REDIS_ENGINE_IMAGE]"
    fi
    print_row "🔥 Firebase CLI & Emulator Suite" "$ENABLE_FIREBASE"
    print_row "🧰 Dev TUI Tools (lazygit, bat, eza)" "$ENABLE_DEV_TOOLS"
    echo -e "${CYAN}------------------------------------------------------------------------${NC}"
    echo ""
}

# Install All Preset
install_all() {
    ENABLE_AI_AGENTS=true
    ENABLE_FLUTTER_ANDROID=true
    ENABLE_EXPO=true
    ENABLE_FASTLANE=true
    ENABLE_KOTLIN=true
    ENABLE_LIGHTHOUSE=true
    ENABLE_WATCHMAN=true
    ENABLE_PLAYWRIGHT=true
    ENABLE_PHP=true
    ENABLE_MYSQL=true
    ENABLE_POSTGRES=true
    ENABLE_MONGO=true
    ENABLE_REDIS=true
    ENABLE_FIREBASE=true
    ENABLE_DEV_TOOLS=true
    ENABLE_COMPOSER=true
    ENABLE_BUN=true
    ENABLE_UV=true
    ENABLE_RUST=true
    ENABLE_GO=true
    ENABLE_DENO=true
    ENABLE_CPP_TOOLCHAIN=true
    ENABLE_ZSH=true
    ENABLE_FISH=true
    ENABLE_VSCODE_WEB=true
    ENABLE_VSCODIUM_WEB=true
    ENABLE_NEOVIM=true
    ENABLE_MICRO=true
    ENABLE_HELIX=true
    ENABLE_WEB_TOOLING=true
    ENABLE_POSTGRES_CLIENT=true
    DB_ENGINE="mysql"
    DB_ENGINE_IMAGE="mysql:8.4"
    REDIS_ENGINE_IMAGE="redis:8-alpine"
    NODE_VERSION="24"
    PHP_VERSION="8.5"
    JAVA_VERSION="21"
    save_config
    echo -e "${GREEN}${BOLD}[🚀] FULL SUPERCHARGED SUITE ENABLED! (All components active).${NC}"
}

# Minimal Preset
install_minimal() {
    ENABLE_AI_AGENTS=true
    ENABLE_FLUTTER_ANDROID=false
    ENABLE_EXPO=true
    ENABLE_FASTLANE=false
    ENABLE_KOTLIN=false
    ENABLE_LIGHTHOUSE=true
    ENABLE_WATCHMAN=false
    ENABLE_PLAYWRIGHT=false
    ENABLE_PHP=false
    ENABLE_MYSQL=false
    ENABLE_POSTGRES=false
    ENABLE_MONGO=false
    ENABLE_REDIS=false
    ENABLE_FIREBASE=false
    ENABLE_DEV_TOOLS=true
    ENABLE_COMPOSER=false
    ENABLE_BUN=true
    ENABLE_UV=true
    ENABLE_RUST=false
    ENABLE_GO=false
    ENABLE_DENO=false
    ENABLE_CPP_TOOLCHAIN=false
    ENABLE_ZSH=true
    ENABLE_FISH=false
    ENABLE_VSCODE_WEB=true
    ENABLE_VSCODIUM_WEB=true
    ENABLE_NEOVIM=true
    ENABLE_MICRO=true
    ENABLE_HELIX=false
    ENABLE_WEB_TOOLING=true
    ENABLE_POSTGRES_CLIENT=false
    DB_ENGINE="mysql"
    DB_ENGINE_IMAGE="mysql:8.4"
    REDIS_ENGINE_IMAGE="redis:8-alpine"
    NODE_VERSION="24"
    PHP_VERSION="8.5"
    JAVA_VERSION="21"
    save_config
    echo -e "${YELLOW}[⚡] MINIMAL CORE SUITE ENABLED! (AI Agents + Node 24 + Expo + Bun + UV + Zsh + Neovim + VS Code/VSCodium Web).${NC}"
}

# Interactive Whiptail Checklist Menu
custom_whiptail_menu() {
    local CHOICE
    CHOICE=$(whiptail --title "Mayanktaker Devbox Custom Component Selection" \
        --checklist "Use Spacebar to toggle items ON/OFF, then press Enter:" 25 85 18 \
        "AI_AGENTS" "20+ AI Agent CLIs (Claude, Kilo, Gemini, Devin, etc)" $([ "$ENABLE_AI_AGENTS" = "true" ] && echo "ON" || echo "OFF") \
        "VSCODE_WEB" "VS Code Web Server (code-server - Microsoft)" $([ "$ENABLE_VSCODE_WEB" = "true" ] && echo "ON" || echo "OFF") \
        "VSCODIUM_WEB" "VSCodium Web Server (open-vsx Telemetry-Free)" $([ "$ENABLE_VSCODIUM_WEB" = "true" ] && echo "ON" || echo "OFF") \
        "FLUTTER_ANDROID" "Flutter SDK, Dart & Android SDK API 35" $([ "$ENABLE_FLUTTER_ANDROID" = "true" ] && echo "ON" || echo "OFF") \
        "EXPO" "React Native Expo CLI & eas-cli" $([ "$ENABLE_EXPO" = "true" ] && echo "ON" || echo "OFF") \
        "FASTLANE" "Fastlane Mobile Release Automation" $([ "$ENABLE_FASTLANE" = "true" ] && echo "ON" || echo "OFF") \
        "KOTLIN" "Kotlin Compiler (kotlinc)" $([ "$ENABLE_KOTLIN" = "true" ] && echo "ON" || echo "OFF") \
        "WATCHMAN" "Watchman React Native Hot Reload" $([ "$ENABLE_WATCHMAN" = "true" ] && echo "ON" || echo "OFF") \
        "PLAYWRIGHT" "Chromium & Playwright Browser Automation" $([ "$ENABLE_PLAYWRIGHT" = "true" ] && echo "ON" || echo "OFF") \
        "LIGHTHOUSE" "Lighthouse Core Web Vitals & PWA Audit" $([ "$ENABLE_LIGHTHOUSE" = "true" ] && echo "ON" || echo "OFF") \
        "PHP" "PHP Engine & Extensions" $([ "$ENABLE_PHP" = "true" ] && echo "ON" || echo "OFF") \
        "COMPOSER" "Composer PHP Package Manager" $([ "$ENABLE_COMPOSER" = "true" ] && echo "ON" || echo "OFF") \
        "BUN" "Bun Fast JS/TS Runtime & PM" $([ "$ENABLE_BUN" = "true" ] && echo "ON" || echo "OFF") \
        "UV" "uv Fast Python Package Manager" $([ "$ENABLE_UV" = "true" ] && echo "ON" || echo "OFF") \
        "RUST" "Rust Toolchain (cargo, rustc, rustup)" $([ "$ENABLE_RUST" = "true" ] && echo "ON" || echo "OFF") \
        "GO" "Go Language (Golang 1.23)" $([ "$ENABLE_GO" = "true" ] && echo "ON" || echo "OFF") \
        "DENO" "Deno TS/JS Runtime" $([ "$ENABLE_DENO" = "true" ] && echo "ON" || echo "OFF") \
        "CPP_TOOLCHAIN" "C/C++ Clang 18, LLVM, CMake & GDB" $([ "$ENABLE_CPP_TOOLCHAIN" = "true" ] && echo "ON" || echo "OFF") \
        "ZSH" "Zsh Shell + Starship Prompt" $([ "$ENABLE_ZSH" = "true" ] && echo "ON" || echo "OFF") \
        "FISH" "Fish Shell" $([ "$ENABLE_FISH" = "true" ] && echo "ON" || echo "OFF") \
        "NEOVIM" "Neovim & Vim Text Editor" $([ "$ENABLE_NEOVIM" = "true" ] && echo "ON" || echo "OFF") \
        "MICRO" "Micro Text Editor" $([ "$ENABLE_MICRO" = "true" ] && echo "ON" || echo "OFF") \
        "HELIX" "Helix Modal Text Editor" $([ "$ENABLE_HELIX" = "true" ] && echo "ON" || echo "OFF") \
        "WEB_TOOLING" "Astro, Next.js, Vite, Tailwind Scaffolding" $([ "$ENABLE_WEB_TOOLING" = "true" ] && echo "ON" || echo "OFF") \
        "MYSQL" "MySQL / MariaDB Container + phpMyAdmin" $([ "$ENABLE_MYSQL" = "true" ] && echo "ON" || echo "OFF") \
        "POSTGRES" "PostgreSQL 17 Container + pgAdmin 4" $([ "$ENABLE_POSTGRES" = "true" ] && echo "ON" || echo "OFF") \
        "MONGO" "MongoDB 8 Container + Mongo Express" $([ "$ENABLE_MONGO" = "true" ] && echo "ON" || echo "OFF") \
        "REDIS" "Redis / KeyDB Cache Container + Redis Commander" $([ "$ENABLE_REDIS" = "true" ] && echo "ON" || echo "OFF") \
        "FIREBASE" "Firebase CLI & Local Emulator Suite" $([ "$ENABLE_FIREBASE" = "true" ] && echo "ON" || echo "OFF") \
        "DEV_TOOLS" "Developer TUI Tools (lazygit, bat, eza, etc)" $([ "$ENABLE_DEV_TOOLS" = "true" ] && echo "ON" || echo "OFF") \
        3>&1 1>&2 2>&3) || return

    ENABLE_AI_AGENTS=false
    ENABLE_VSCODE_WEB=false
    ENABLE_VSCODIUM_WEB=false
    ENABLE_FLUTTER_ANDROID=false
    ENABLE_EXPO=false
    ENABLE_FASTLANE=false
    ENABLE_KOTLIN=false
    ENABLE_WATCHMAN=false
    ENABLE_PLAYWRIGHT=false
    ENABLE_LIGHTHOUSE=false
    ENABLE_PHP=false
    ENABLE_COMPOSER=false
    ENABLE_BUN=false
    ENABLE_UV=false
    ENABLE_RUST=false
    ENABLE_GO=false
    ENABLE_DENO=false
    ENABLE_CPP_TOOLCHAIN=false
    ENABLE_ZSH=false
    ENABLE_FISH=false
    ENABLE_NEOVIM=false
    ENABLE_MICRO=false
    ENABLE_HELIX=false
    ENABLE_WEB_TOOLING=false
    ENABLE_MYSQL=false
    ENABLE_POSTGRES=false
    ENABLE_MONGO=false
    ENABLE_REDIS=false
    ENABLE_FIREBASE=false
    ENABLE_DEV_TOOLS=false

    for item in $CHOICE; do
        case $(echo "$item" | tr -d '"') in
            AI_AGENTS) ENABLE_AI_AGENTS=true ;;
            VSCODE_WEB) ENABLE_VSCODE_WEB=true ;;
            VSCODIUM_WEB) ENABLE_VSCODIUM_WEB=true ;;
            FLUTTER_ANDROID) ENABLE_FLUTTER_ANDROID=true ;;
            EXPO) ENABLE_EXPO=true ;;
            FASTLANE) ENABLE_FASTLANE=true ;;
            KOTLIN) ENABLE_KOTLIN=true ;;
            WATCHMAN) ENABLE_WATCHMAN=true ;;
            PLAYWRIGHT) ENABLE_PLAYWRIGHT=true ;;
            LIGHTHOUSE) ENABLE_LIGHTHOUSE=true ;;
            PHP) ENABLE_PHP=true ;;
            COMPOSER) ENABLE_COMPOSER=true ;;
            BUN) ENABLE_BUN=true ;;
            UV) ENABLE_UV=true ;;
            RUST) ENABLE_RUST=true ;;
            GO) ENABLE_GO=true ;;
            DENO) ENABLE_DENO=true ;;
            CPP_TOOLCHAIN) ENABLE_CPP_TOOLCHAIN=true ;;
            ZSH) ENABLE_ZSH=true ;;
            FISH) ENABLE_FISH=true ;;
            NEOVIM) ENABLE_NEOVIM=true ;;
            MICRO) ENABLE_MICRO=true ;;
            HELIX) ENABLE_HELIX=true ;;
            WEB_TOOLING) ENABLE_WEB_TOOLING=true ;;
            MYSQL) ENABLE_MYSQL=true ;;
            POSTGRES) ENABLE_POSTGRES=true ;;
            MONGO) ENABLE_MONGO=true ;;
            REDIS) ENABLE_REDIS=true ;;
            FIREBASE) ENABLE_FIREBASE=true ;;
            DEV_TOOLS) ENABLE_DEV_TOOLS=true ;;
        esac
    done

    save_config
}

# Main Wizard Menu Router
run_wizard() {
    load_config
    show_banner
    show_summary

    echo -e "${BOLD}Choose a Setup Wizard Option:${NC}"
    echo -e "  ${GREEN}${BOLD}[1] 🚀 INSTALL ALL (Full Supercharged Suite - Recommended Default)${NC}"
    echo -e "  ${CYAN}[2] 🎛️  Custom Selection (Toggle components ON/OFF via checklist)${NC}"
    echo -e "  ${YELLOW}[3] ⚡ Minimal Suite (Core AI Agents + Node 24 + Expo + Bun + UV + VS Code/VSCodium Web)${NC}"
    echo -e "  ${CYAN}[4] ⚙️ Customize Stack Versions (Node $NODE_VERSION, PHP $PHP_VERSION, Java $JAVA_VERSION)${NC}"
    echo -e "  ${CYAN}[5] 🗄️ Database & Cache Options (MySQL/MariaDB, PostgreSQL, MongoDB, Redis/KeyDB)${NC}"
    echo -e "  ${CYAN}[6] 💻 Shells & Web/Terminal Editors (VS Code MS vs VSCodium Open-VSX, Shells, Editors)${NC}"
    echo -e "  ${CYAN}[7] 🔑 Configure API Keys (.env helper)${NC}"
    echo -e "  ${CYAN}[8] 🔒 Run Host Permissions & Docker Group Pre-Check${NC}"
    echo -e "  [9] 🚪 Exit without changes"
    echo ""
    read -p "Select option [1-9]: " main_choice

    case "$main_choice" in
        1)
            install_all
            ;;
        2)
            if [ -t 0 ] && command -v whiptail >/dev/null 2>&1; then
                custom_whiptail_menu
            else
                echo -e "${YELLOW}Whiptail GUI menu active. Running checklist...${NC}"
                custom_whiptail_menu
            fi
            ;;
        3)
            install_minimal
            ;;
        4)
            select_stack_versions
            run_wizard
            return
            ;;
        5)
            select_db_engines
            run_wizard
            return
            ;;
        6)
            select_shells_editors
            run_wizard
            return
            ;;
        7)
            configure_keys
            run_wizard
            return
            ;;
        8)
            run_permissions_check
            run_wizard
            return
            ;;
        9)
            echo -e "${YELLOW}Exited without changing configuration.${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}Invalid selection.${NC}"
            exit 1
            ;;
    esac

    show_banner
    show_summary

    read -p "Would you like to build and start Devbox now? (Y/n): " confirm_build
    case "$confirm_build" in
        [nN]*)
            echo -e "${YELLOW}Setup complete! Run './manage.sh build && ./manage.sh up' when ready.${NC}"
            ;;
        *)
            echo -e "${GREEN}[+] Starting build and launch sequence...${NC}"
            ./manage.sh build
            ./manage.sh up
            ;;
    esac
}

run_wizard
